package query

import (
	"bytes"
	"context"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"

)

// RunOptions configures the Run verb.
type RunOptions struct {
	SQL   string
	Out   string // optional dataset slug to materialize results into
	Force bool   // overwrite existing dataset page if true
}

var rejectAttach = regexp.MustCompile(`(?i)\bATTACH\b`)

// Run executes an ad-hoc SQL query via DuckDB and either prints the result as
// a markdown table to stdout, or materializes it as a sibling dataset page
// when opts.Out is non-empty.
func (r *Runner) Run(ctx context.Context, opts RunOptions, stdout io.Writer) error {
	if opts.SQL == "" {
		return fmt.Errorf("QUERY|ERROR|missing SQL")
	}
	if rejectAttach.MatchString(opts.SQL) {
		return fmt.Errorf("QUERY|ERROR|external attach not supported until stage 3")
	}

	rewritten, tmps, err := ResolveSQL(r.RepoRoot, opts.SQL)
	if err != nil {
		return err
	}
	defer CleanupTemps(tmps)

	if opts.Out == "" {
		// Just print formatted table.
		out, code, err := r.DuckDB.Run(ctx, rewritten, "csv")
		if err != nil {
			return fmt.Errorf("QUERY|ERROR|duckdb exec: %w", err)
		}
		if code != 0 {
			return fmt.Errorf("QUERY|ERROR|duckdb exit %d: %s", code, strings.TrimSpace(out))
		}
		result, parseErr := parseCSVOutput(out)
		if parseErr != nil {
			return parseErr
		}
		fmt.Fprint(stdout, FormatTable(result))
		return nil
	}

	// Materialize to a dataset page.
	if !reSlug.MatchString(opts.Out) {
		return fmt.Errorf("QUERY|ERROR|invalid slug: %s", opts.Out)
	}
	target := filepath.Join(r.DatasetDir(), opts.Out+".md")
	if _, statErr := os.Stat(target); statErr == nil && !opts.Force {
		return fmt.Errorf("QUERY|ERROR|target exists: %s (use --force)", target)
	}

	out, code, err := r.DuckDB.Run(ctx, rewritten, "csv")
	if err != nil {
		return fmt.Errorf("QUERY|ERROR|duckdb exec: %w", err)
	}
	if code != 0 {
		return fmt.Errorf("QUERY|ERROR|duckdb exit %d: %s", code, strings.TrimSpace(out))
	}

	result, parseErr := parseCSVOutput(out)
	if parseErr != nil {
		return parseErr
	}

	if err := r.materializeDataset(opts.Out, opts.SQL, result, target); err != nil {
		return err
	}

	rowsN := len(result.Rows)
	fmt.Fprintf(stdout, "QUERY|MATERIALIZED|%s|rows=%d\n", target, rowsN)
	return nil
}

// materializeDataset writes a type:dataset page with inline CSV containing
// the query result. Matches cmd_run bash output byte-for-byte.
func (r *Runner) materializeDataset(slug, sql string, result Result, target string) error {
	// Build CSV content from result.
	var csvBuf bytes.Buffer
	w := csv.NewWriter(&csvBuf)
	w.Write(result.Columns)
	for _, row := range result.Rows {
		w.Write(row)
	}
	w.Flush()
	csvContent := csvBuf.String()

	today := r.Today
	if today == "" {
		today = nowDate()
	}

	// Build sources list from SQL (dataset slugs referenced).
	slugs := refsFromSQL(sql)
	sourcesList := strings.Join(slugs, ",")

	rowsN := len(result.Rows)

	var sb strings.Builder
	sb.WriteString("---\n")
	fmt.Fprintf(&sb, "title: \"%s\"\n", slug)
	fmt.Fprintf(&sb, "date: %s\n", today)
	fmt.Fprintf(&sb, "last_updated: %s\n", today)
	sb.WriteString("type: dataset\n")
	sb.WriteString("tags: []\n")
	sb.WriteString("storage: inline\n")
	sb.WriteString("format: csv\n")
	fmt.Fprintf(&sb, "rows: %s\n", strconv.Itoa(rowsN))
	fmt.Fprintf(&sb, "sources: [%s]\n", sourcesList)
	sb.WriteString("draft: false\n")
	sb.WriteString("---\n\n")
	fmt.Fprintf(&sb, "# %s\n\n", slug)
	sb.WriteString("<!-- generated by query.sh — do not edit ## Data by hand -->\n\n")
	sb.WriteString("## Schema\n\n")
	sb.WriteString("## Data\n")
	sb.WriteString("```csv\n")
	sb.WriteString(csvContent)
	sb.WriteString("```\n\n")
	sb.WriteString("## Provenance\n\n")
	fmt.Fprintf(&sb, "Generated by `scripts/query.sh run --out=%s`.\n\n", slug)
	sb.WriteString("## Related\n\n")
	sb.WriteString("## Sources\n")

	content := []byte(sb.String())
	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return err
	}
	return os.WriteFile(target, content, 0644)
}

// parseCSVOutput parses the CSV output from DuckDB into a Result.
func parseCSVOutput(csvData string) (Result, error) {
	r := csv.NewReader(strings.NewReader(csvData))
	r.FieldsPerRecord = -1
	records, err := r.ReadAll()
	if err != nil {
		return Result{}, fmt.Errorf("parse csv: %w", err)
	}
	if len(records) == 0 {
		return Result{}, nil
	}
	cols := records[0]
	rows := records[1:]
	// Normalize nil rows.
	if rows == nil {
		rows = [][]string{}
	}
	return Result{Columns: cols, Rows: rows}, nil
}

// parseJSONRows parses DuckDB JSON output (array of objects) into a Result.
func parseJSONRows(jsonData string) (Result, error) {
	jsonData = strings.TrimSpace(jsonData)
	if jsonData == "" || jsonData == "null" {
		return Result{}, nil
	}
	var rows []map[string]interface{}
	if err := json.Unmarshal([]byte(jsonData), &rows); err != nil {
		return Result{}, fmt.Errorf("parse json: %w", err)
	}
	if len(rows) == 0 {
		return Result{}, nil
	}
	// Extract columns from first row.
	cols := make([]string, 0)
	for k := range rows[0] {
		cols = append(cols, k)
	}
	// Sort for determinism.
	sortStringsQuery(cols)

	result := Result{Columns: cols}
	for _, row := range rows {
		r := make([]string, len(cols))
		for i, c := range cols {
			v := row[c]
			if v == nil {
				r[i] = ""
			} else {
				r[i] = fmt.Sprint(v)
			}
		}
		result.Rows = append(result.Rows, r)
	}
	return result, nil
}

func sortStringsQuery(ss []string) {
	for i := 1; i < len(ss); i++ {
		for j := i; j > 0 && ss[j] < ss[j-1]; j-- {
			ss[j], ss[j-1] = ss[j-1], ss[j]
		}
	}
}

func nowDate() string {
	// Use a fixed import-time value; callers should set Runner.Today.
	return "1970-01-01"
}

// materialize writes result as an inline dataset page. This is the public entry
// point used by the run verb when --out is set.
func (r *Runner) materialize(outSlug string, sql string, result Result) error {
	target := filepath.Join(r.DatasetDir(), outSlug+".md")
	return r.materializeDataset(outSlug, sql, result, target)
}
