#!/usr/bin/env bash
# scripts/query.sh — DuckDB query layer CLI.
# Subcommands: run, new, render, render-one, fence-render.
set -uo pipefail

REPO_ROOT="${AWIKI_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$REPO_ROOT"

ENGINE="$REPO_ROOT/scripts/lib/query-engine.sh"
# shellcheck source=lib/managed-region.sh
source "$REPO_ROOT/scripts/lib/managed-region.sh"

note() { echo "QUERY|$*"; }
die()  { echo "QUERY|ERROR|$*" >&2; exit 1; }

cmd_run() {
  local sql=""
  local out=""
  local force=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out=*)   out="${1#--out=}" ;;
      --force)   force=1 ;;
      --)        shift; break ;;
      -*)        die "unknown flag: $1" ;;
      *)         sql="$1" ;;
    esac
    shift
  done
  [[ -n "$sql" ]] || die "missing SQL"
  if [[ -z "$out" ]]; then
    bash "$ENGINE" run "$sql"
    return $?
  fi

  local SLUG_RE='^[a-z0-9][a-z0-9-]*$'
  [[ "$out" =~ $SLUG_RE ]] || die "invalid slug: $out"
  local target="content/datasets/$out.md"
  if [[ -f "$target" && $force -eq 0 ]]; then
    echo "QUERY|ERROR|target exists: $target (use --force)" >&2
    exit 7
  fi

  local tmp_rows; tmp_rows="$(mktemp)"
  bash "$ENGINE" run "$sql" > "$tmp_rows"
  local rc=$?
  [[ $rc -eq 0 ]] || { rm -f "$tmp_rows"; exit $rc; }

  # Convert JSON rows -> CSV.
  local tmp_csv; tmp_csv="$(mktemp --suffix=.csv 2>/dev/null || mktemp -t qcsv)"
  python3 - "$tmp_rows" "$tmp_csv" <<'PY'
import csv, json, sys, pathlib
rows = json.loads(pathlib.Path(sys.argv[1]).read_text() or "[]")
with open(sys.argv[2], "w", newline="") as f:
    if not rows:
        f.write("")
        sys.exit(0)
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader()
    for r in rows:
        w.writerow(r)
PY

  local sources_csv
  sources_csv="$(printf '%s' "$sql" | python3 "$REPO_ROOT/scripts/lib/query-resolve.py" | paste -sd, -)"
  local hash_val
  hash_val="$(bash "$ENGINE" hash "$sql")"
  local today; today="$(date '+%Y-%m-%d')"
  local rows_n; rows_n=$(($(wc -l < "$tmp_csv") - 1))
  [[ $rows_n -lt 0 ]] && rows_n=0

  {
    printf -- '---\n'
    printf -- 'title: "%s"\n' "$out"
    printf -- 'date: %s\n' "$today"
    printf -- 'last_updated: %s\n' "$today"
    printf -- 'type: dataset\n'
    printf -- 'tags: []\n'
    printf -- 'storage: inline\n'
    printf -- 'format: csv\n'
    printf -- 'rows: %s\n' "$rows_n"
    printf -- 'sources: [%s]\n' "$sources_csv"
    printf -- 'query: sha256-%s\n' "$hash_val"
    printf -- 'draft: false\n'
    printf -- '---\n\n'
    printf -- '# %s\n\n' "$out"
    printf -- '<!-- generated by query.sh — do not edit ## Data by hand -->\n\n'
    printf -- '## Schema\n\n'
    printf -- '## Data\n'
    printf -- '```csv\n'
    cat "$tmp_csv"
    printf -- '```\n\n'
    printf -- '## Provenance\n\n'
    printf -- 'Generated by `scripts/query.sh run --out=%s`.\n\n' "$out"
    printf -- '## Related\n\n'
    printf -- '## Sources\n'
  } > "$target"
  rm -f "$tmp_rows" "$tmp_csv"
  note "MATERIALIZED|$target|rows=$rows_n"
}

_query_page_sql() {
  python3 - "$1" <<'PY'
import re, sys, pathlib
text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
m = re.search(r"```sql\s*\n(.*?)\n```", text, re.S)
print(m.group(1) if m else "", end="")
PY
}

_query_page_out() {
  python3 - "$1" <<'PY'
import re, sys, pathlib
text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
m = re.search(r"^out:\s*(\S+)", text, re.M)
print(m.group(1) if m else "", end="")
PY
}

cmd_render_one() {
  local slug="${1:-}"
  [[ -n "$slug" ]] || die "missing query slug"
  local page="content/queries/$slug.md"
  [[ -f "$page" ]] || die "no such query: $page"
  local sql out
  sql="$(_query_page_sql "$page")"
  out="$(_query_page_out "$page")"
  [[ -n "$sql" ]] || die "no \`\`\`sql fence in $page"
  [[ -n "$out" ]] || die "no out: <slug> in frontmatter of $page"

  # Determinism guard.
  if ! printf '%s' "$sql" | python3 "$REPO_ROOT/scripts/lib/query-determinism.py" 2>&1; then
    exit 6
  fi

  # Materialize via cmd_run --out --force.
  cmd_run "$sql" --out="$out" --force

  # Update sql_hash + sidecar.
  local h; h="$(bash "$ENGINE" hash "$sql")"
  python3 - "$page" "$h" <<'PY'
import re, sys, pathlib
page = pathlib.Path(sys.argv[1])
h = sys.argv[2]
text = page.read_text(encoding="utf-8")
text2 = re.sub(r'^sql_hash:.*$', f'sql_hash: sha256-{h}', text, count=1, flags=re.M)
page.write_text(text2, encoding="utf-8")
PY
  printf 'sha256-%s\n' "$h" > "content/queries/$slug.sql.hash"
  note "RENDER|$slug|out=$out|hash=sha256-$h"
}

cmd_render() {
  shopt -s nullglob
  local rc=0
  for page in content/queries/*.md; do
    local slug; slug="$(basename "$page" .md)"
    cmd_render_one "$slug" || rc=$?
  done
  return $rc
}

cmd_new() {
  local slug="" out=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out=*) out="${1#--out=}" ;;
      --) shift; break ;;
      -*) die "unknown flag: $1" ;;
      *) slug="$1" ;;
    esac
    shift
  done
  local SLUG_RE='^[a-z0-9][a-z0-9-]*$'
  [[ -n "$slug" ]] || die "missing <slug>"
  [[ "$slug" =~ $SLUG_RE ]] || die "invalid slug: $slug"
  [[ -n "$out" ]]  || die "--out=<dataset-slug> required"
  [[ "$out" =~ $SLUG_RE ]] || die "invalid out slug: $out"
  local page="content/queries/$slug.md"
  [[ ! -e "$page" ]] || die "$page already exists"
  mkdir -p content/queries
  local today; today="$(date '+%Y-%m-%d')"
  cat > "$page" <<EOF
---
title: "$slug"
date: $today
last_updated: $today
type: query
sources: []
out: $out
privacy: internal
deterministic: true
sql_hash: ""
draft: false
---

# $slug

<!-- describe what this query answers -->

## SQL

\`\`\`sql
SELECT 1 AS placeholder
ORDER BY 1
\`\`\`

## Notes
EOF
  note "NEW|$page"
}

_iter_fences() {
  # Print TSV: <page>\t<id>\t<base64-sql>
  python3 - <<'PY'
import re, base64, pathlib
for page in pathlib.Path("content").rglob("*.md"):
    text = page.read_text(encoding="utf-8")
    for m in re.finditer(
        r'```sql\s+awiki-query\s+id="([a-z0-9][a-z0-9-]*)"\s*\n(.*?)\n```',
        text, re.S,
    ):
        sql_b64 = base64.b64encode(m.group(2).encode()).decode()
        print(f"{page}\t{m.group(1)}\t{sql_b64}")
PY
}

cmd_fence_render() {
  local rc=0
  declare -A page_hashes
  while IFS=$'\t' read -r page fid sql_b64; do
    [[ -z "$page" ]] && continue
    local sql; sql="$(printf '%s' "$sql_b64" | base64 --decode)"
    local rows; rows="$(bash "$ENGINE" run "$sql")" || { rc=$?; continue; }
    local body_md; body_md="$(printf '%s' "$rows" | python3 "$REPO_ROOT/scripts/lib/query-format.py" --format=md)"
    local body_file; body_file="$(mktemp)"
    printf '%s' "$body_md" > "$body_file"
    managed_region_replace "$page" query-result "$fid" "$body_file"
    rm -f "$body_file"
    local h; h="$(bash "$ENGINE" hash "$sql")"
    page_hashes["$page"]+="$fid:$h"$'\n'
    note "FENCE-RENDER|$page|id=$fid|hash=sha256-$h"
  done < <(_iter_fences)

  for page in "${!page_hashes[@]}"; do
    python3 - "$page" "${page_hashes[$page]}" <<'PY'
import json, sys, pathlib
page = pathlib.Path(sys.argv[1])
side = page.with_suffix(".queries.json")
entries = {}
for line in sys.argv[2].splitlines():
    if not line.strip(): continue
    fid, h = line.split(":", 1)
    entries[fid] = f"sha256-{h}"
side.write_text(json.dumps(entries, sort_keys=True, indent=2) + "\n")
PY
  done
  return $rc
}

main() {
  local cmd="${1:-}"
  shift || true
  case "$cmd" in
    run)           cmd_run "$@" ;;
    new)           cmd_new "$@" ;;
    render)        cmd_render "$@" ;;
    render-one)    cmd_render_one "$@" ;;
    fence-render)  cmd_fence_render "$@" ;;
    "")            die "usage: query.sh <run|new|render|render-one|fence-render>" ;;
    *)             die "unknown subcommand: $cmd" ;;
  esac
}

main "$@"
