#!/usr/bin/env bash
# scripts/query.sh — DuckDB query layer CLI.
# Subcommands: run, new, render, render-one, fence-render.
set -uo pipefail

REPO_ROOT="${AWIKI_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$REPO_ROOT"

ENGINE="$REPO_ROOT/scripts/lib/query-engine.sh"

note() { echo "QUERY|$*"; }
die()  { echo "QUERY|ERROR|$*" >&2; exit 1; }

cmd_run() {
  local sql=""
  local out=""
  local force=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --out=*)   out="${1#--out=}" ;;
      --force)   force=1 ;;
      --)        shift; break ;;
      -*)        die "unknown flag: $1" ;;
      *)         sql="$1" ;;
    esac
    shift
  done
  [[ -n "$sql" ]] || die "missing SQL"
  if [[ -z "$out" ]]; then
    bash "$ENGINE" run "$sql"
    return $?
  fi

  local SLUG_RE='^[a-z0-9][a-z0-9-]*$'
  [[ "$out" =~ $SLUG_RE ]] || die "invalid slug: $out"
  local target="content/datasets/$out.md"
  if [[ -f "$target" && $force -eq 0 ]]; then
    echo "QUERY|ERROR|target exists: $target (use --force)" >&2
    exit 7
  fi

  local tmp_rows; tmp_rows="$(mktemp)"
  bash "$ENGINE" run "$sql" > "$tmp_rows"
  local rc=$?
  [[ $rc -eq 0 ]] || { rm -f "$tmp_rows"; exit $rc; }

  # Convert JSON rows -> CSV.
  local tmp_csv; tmp_csv="$(mktemp --suffix=.csv 2>/dev/null || mktemp -t qcsv)"
  python3 - "$tmp_rows" "$tmp_csv" <<'PY'
import csv, json, sys, pathlib
rows = json.loads(pathlib.Path(sys.argv[1]).read_text() or "[]")
with open(sys.argv[2], "w", newline="") as f:
    if not rows:
        f.write("")
        sys.exit(0)
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader()
    for r in rows:
        w.writerow(r)
PY

  local sources_csv
  sources_csv="$(printf '%s' "$sql" | python3 "$REPO_ROOT/scripts/lib/query-resolve.py" | paste -sd, -)"
  local hash_val
  hash_val="$(bash "$ENGINE" hash "$sql")"
  local today; today="$(date '+%Y-%m-%d')"
  local rows_n; rows_n=$(($(wc -l < "$tmp_csv") - 1))
  [[ $rows_n -lt 0 ]] && rows_n=0

  {
    printf -- '---\n'
    printf -- 'title: "%s"\n' "$out"
    printf -- 'date: %s\n' "$today"
    printf -- 'last_updated: %s\n' "$today"
    printf -- 'type: dataset\n'
    printf -- 'tags: []\n'
    printf -- 'storage: inline\n'
    printf -- 'format: csv\n'
    printf -- 'rows: %s\n' "$rows_n"
    printf -- 'sources: [%s]\n' "$sources_csv"
    printf -- 'query: sha256-%s\n' "$hash_val"
    printf -- 'draft: false\n'
    printf -- '---\n\n'
    printf -- '# %s\n\n' "$out"
    printf -- '<!-- generated by query.sh — do not edit ## Data by hand -->\n\n'
    printf -- '## Schema\n\n'
    printf -- '## Data\n'
    printf -- '```csv\n'
    cat "$tmp_csv"
    printf -- '```\n\n'
    printf -- '## Provenance\n\n'
    printf -- 'Generated by `scripts/query.sh run --out=%s`.\n\n' "$out"
    printf -- '## Related\n\n'
    printf -- '## Sources\n'
  } > "$target"
  rm -f "$tmp_rows" "$tmp_csv"
  note "MATERIALIZED|$target|rows=$rows_n"
}

main() {
  local cmd="${1:-}"
  shift || true
  case "$cmd" in
    run)           cmd_run "$@" ;;
    "")            die "usage: query.sh <run|new|render|render-one|fence-render>" ;;
    *)             die "unknown subcommand: $cmd" ;;
  esac
}

main "$@"
